post_stops <- extract.samples(out_stops)
# Compute the actual scale of the deviations for all routes
route_deviations <- colMeans(post_stops$z_route * post_stops$sigma_route)
hist(route_deviations, breaks = 30, main = "Distribution of Route-Level Deviations", 
     xlab = "Log-Odds Shift per Route", col = "skyblue")
abline(v = 0, col = "red", linetype = "dashed", lwd = 2)

precis(out_stops)

# Fit a model containing ONLY the fixed environmental effects
model_stops_fixed_only <- ulam(
  alist(
    k_stops ~ custom( fisher_hyper_lpmf(k_stops[i] | exp(log_omega[i]), m1_stops[i], m2_stops[i], S_total[i]) ),
    log_omega <- b0 + b_res*res_div + b_hab*hab_pref + b_sym*sympatry + b_prod*prod,
    b0 ~ dnorm(0, 1), b_res ~ dnorm(0, 1), b_hab ~ dnorm(0, 1), b_sym ~ dnorm(0, 1), b_prod ~ dnorm(0, 1)
  ), data = dat_list_stops, chains = 4, cores = 4, iter = 4000, sample = FALSE
)

# Extract the autogenerated text
stan_code_stops <- stancode(model_stops_fixed_only)

# Paste the file-loaded functions block to the top of the text string
full_stan_code_stops <- paste0(likelihood_pmf, "\n", stan_code_stops)

# Run the compiled model using rstan
out_stops_fixed_only <- stan(
  model_code = full_stan_code_stops,
  data = dat_list_stops,
  chains = 4, 
  cores = 4,
  iter = 4000,
  seed = 1
)

precis(out_stops_fixed_only)
compare(out_stops, out_stops_fixed_only)
